"""
Generate Gate D layer-level verification vectors.

Outputs:
  Build/golden_first_add.bin
  Build/full_instructions_gate_d_first_add.txt
  Build/npu_program_gate_d_first_add.hex
  Build/golden_sppf_input.bin
  Build/golden_sppf_output.bin
  Build/full_instructions_gate_d_sppf.txt
  Build/npu_program_gate_d_sppf.hex

The golden tensors are generated by the frozen Python ISS contract using the
same seed-0 640x640 input image and weights.bin.
"""
import hashlib
from pathlib import Path

import numpy as np

from assembler import text_to_hex_full
from npu_iss import NPU_ISS


ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "Build"
HALT = "OP:HALT   | IN:0x00000000 | WGT:0x00000000 | OUT:0x00000000 | FLAGS:0x0 | STRIDE:0 | PAD:0 | KERNEL:0"


def sha256(path):
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def write_text_program(instr_path, hex_path, lines):
    instr_path.write_text("\n".join(lines) + "\n")
    text_to_hex_full(str(instr_path), str(hex_path))


def layer_by_instr(iss, instr_idx, op):
    matches = [(idx, name, addr, arr) for idx, name, addr, arr in iss.layers
               if idx == instr_idx and name == op]
    if len(matches) != 1:
        raise RuntimeError(f"Expected one layer for instr_idx={instr_idx} op={op}, got {len(matches)}")
    return matches[0]


def main():
    BUILD.mkdir(parents=True, exist_ok=True)
    instrs = [ln.strip() for ln in (BUILD / "full_instructions.txt").read_text().splitlines()
              if "|" in ln]
    weights = (BUILD / "weights.bin").read_bytes()

    rng = np.random.default_rng(0)
    img = rng.integers(0, 256, size=3 * 640 * 640, dtype=np.uint8)
    input_path = BUILD / "input_seed0.bin"
    input_path.write_bytes(img.tobytes(order="C"))

    iss = NPU_ISS(weights)
    iss.run(instrs, img)

    # First residual ADD is full_instructions.txt line 19, zero-based idx 18.
    _, _, first_add_addr, first_add = layer_by_instr(iss, 18, "ADD")
    if first_add_addr != 0x00000000 or first_add.shape != (16, 160, 160):
        raise RuntimeError(f"Unexpected first ADD addr/shape: 0x{first_add_addr:08X} {first_add.shape}")

    first_add_golden = BUILD / "golden_first_add.bin"
    first_add_golden.write_bytes(first_add.astype(np.uint8, copy=False).tobytes(order="C"))
    write_text_program(
        BUILD / "full_instructions_gate_d_first_add.txt",
        BUILD / "npu_program_gate_d_first_add.hex",
        instrs[:19] + [HALT],
    )

    # SPPF block-level verification starts from the tensor produced by
    # full_instructions.txt line 123 (zero-based idx 122), then executes the
    # three max-pools, concat staging, and final SPPF 1x1 CONV through line 140.
    _, _, sppf_input_addr, sppf_input = layer_by_instr(iss, 122, "CONV")
    _, _, sppf_output_addr, sppf_output = layer_by_instr(iss, 139, "CONV")
    if sppf_input_addr != 0x00019000 or sppf_input.shape != (128, 20, 20):
        raise RuntimeError(f"Unexpected SPPF input addr/shape: 0x{sppf_input_addr:08X} {sppf_input.shape}")
    if sppf_output_addr != 0x00000000 or sppf_output.shape != (256, 20, 20):
        raise RuntimeError(f"Unexpected SPPF output addr/shape: 0x{sppf_output_addr:08X} {sppf_output.shape}")

    sppf_input_path = BUILD / "golden_sppf_input.bin"
    sppf_output_path = BUILD / "golden_sppf_output.bin"
    sppf_input_path.write_bytes(sppf_input.astype(np.uint8, copy=False).tobytes(order="C"))
    sppf_output_path.write_bytes(sppf_output.astype(np.uint8, copy=False).tobytes(order="C"))

    sppf_lines = [
        "OP:DMA_LD | DRAM:0x00000000 | SRAM:0x00019000 | SIZE:0x0000C800",
        *instrs[123:140],
        HALT,
    ]
    write_text_program(
        BUILD / "full_instructions_gate_d_sppf.txt",
        BUILD / "npu_program_gate_d_sppf.hex",
        sppf_lines,
    )

    for path in [
        input_path,
        first_add_golden,
        BUILD / "full_instructions_gate_d_first_add.txt",
        BUILD / "npu_program_gate_d_first_add.hex",
        sppf_input_path,
        sppf_output_path,
        BUILD / "full_instructions_gate_d_sppf.txt",
        BUILD / "npu_program_gate_d_sppf.hex",
    ]:
        print(f"Wrote {path.relative_to(ROOT)} size={path.stat().st_size} sha256={sha256(path)}")


if __name__ == "__main__":
    main()
