

run: 
	python main.py

sim:
	python npu_iss.py

valid:
	python validation.py

clean:
	rm -f	../Build/full_instructions.txt \
			../Build/cpu_runtime.py \
			../Build/npu_program.hex \
			../Build/weights.bin \
			../Build/weights.hex \
			../Build/iss_layers.npz \
			../Build/mapping.txt